name: shoply-services

services:

  postgres:
    image: postgres:17
    container_name: shoply_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=shoply_auth,shoply_user,shoply_catalog,shoply_inventory,shoply_order,shoply_payment,shoply_shipping,shoply_review,shoply_notification,shoply_search,shoply_pricing
    ports:
      - "5432:5432"
    networks:
      - shoply-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 2s
      retries: 20
    volumes:
      - shoply_postgres_data:/var/lib/postgresql/data
      - ./server/scripts/init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    command: postgres -c listen_addresses='*'
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  api-gateway:
    build: 
      context: .
      dockerfile: server/api-gateway/Dockerfile
    container_name: api-gateway
    restart: unless-stopped
    environment:
      - PORT=8000
      - AUTH_SERVICE_URL=http://auth-service:8001
      - USER_SERVICE_URL=http://user-service:8002
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    networks:
      - shoply-network
    develop:
      watch:
        - action: rebuild
          path: ./server/api-gateway/package.json
        - action: rebuild
          path: ./server/api-gateway/yarn.lock
        - action: sync
          path: ./server/api-gateway/src
          target: /app/src

  auth-service:
    build: 
      context: .
      dockerfile: server/auth-service/Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/shoply_auth?schema=public
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shoply-network
    command: sh -c "yarn db:deploy && yarn dev"
    # command: sh -c "yarn db:migrate && yarn dev"
    develop:
      watch:
        - action: rebuild
          path: ./server/auth-service/package.json
        - action: rebuild
          path: ./server/auth-service/yarn.lock
        - action: rebuild
          path: ./server/auth-service/prisma/schema.prisma
        - action: rebuild
          path: ./server/auth-service/prisma.config.ts
        - action: sync
          path: ./server/auth-service/src
          target: /app/src

networks:
  shoply-network:
    driver: bridge
    name: shoply-network

volumes:
  shoply_postgres_data:
    name: shoply_postgres_data