import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import { NavigationProvider } from "@/context/NavigationContext";
import BottomNav from "@/components/BottomNav";
import { Toaster } from "@/components/ui/sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StoreFrontLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <NavigationProvider>
        {children}
      </NavigationProvider >
      <Suspense>
        <Footer />
      </Suspense>
      <BottomNav />
      <Toaster />
    </>
  );
}
